% /a/ks/b/matlab/panera21/cr_x_is_noon55_enh.m

% Create enhanced training data for last 20 days from 9 original features and rolling_corr values

% calculate the end index:
is_end = length(ip_noon55.ydate) - 20
% Check its date:
ip_noon55(is_end,{'ydatestr'})
% Above date should match date of ip-is-data in noon55.m:
otherdate = datestr(is_endDate2)

is_data_noon55_enh_w0 = ip_noon55(1:is_end,:);

% Weight the data

is_data_noon55_enh_w1 = is_data_noon55_enh_w0( is_end-1*251:is_end, : ) ;
is_data_noon55_enh_w2 = is_data_noon55_enh_w0( is_end-2*251:is_end, : ) ;
is_data_noon55_enh_w3 = is_data_noon55_enh_w0( is_end-3*251:is_end, : ) ;
is_data_noon55_enh_w4 = is_data_noon55_enh_w0( is_end-4*251:is_end, : ) ;
is_data_noon55_enh_w5 = is_data_noon55_enh_w0( is_end-5*251:is_end, : ) ;
is_data_noon55_enh_w10 = is_data_noon55_enh_w0( is_end-10*251:is_end, : ) ;
is_data_noon55_enh_w15 = is_data_noon55_enh_w0( is_end-15*251:is_end, : ) ;
is_data_noon55_enh_w20 = is_data_noon55_enh_w0( is_end-20*251:is_end, : ) ;

is_data_noon55_enh = vertcat(is_data_noon55_enh_w0, ... 
  is_data_noon55_enh_w1, ... 
  is_data_noon55_enh_w2, ... 
  is_data_noon55_enh_w3, ... 
  is_data_noon55_enh_w4, ... 
  is_data_noon55_enh_w5, ... 
  is_data_noon55_enh_w10, ... 
  is_data_noon55_enh_w15, ... 
  is_data_noon55_enh_w20);

% I like a table here so I can see the data:
x_is_noon55_enh_t = is_data_noon55_enh(:,{...
'cpma'     ...
,'n1dg1'   ...
,'n1dg2'   ...
,'n1dg3'   ...
,'n2dlagd' ... 
,'n1wlagd' ... 
,'n2wlagd' ... 
,'n1mlagd' ... 
,'n2mlagd' ...
,'prob_1d' ...
,'prob_2d' ...
,'prob_1w' ...
,'corr1d'  ...
,'corr2d'  ...
,'corr1w'  ...
});

yvalue1d_is = table2array(is_data_noon55_enh(:,{'yvalue1d'}));
yvalue2d_is = table2array(is_data_noon55_enh(:,{'yvalue2d'}));
yvalue1w_is = table2array(is_data_noon55_enh(:,{'yvalue1w'}));

% mnrfit() wants an array not a table:
x_is_noon55_enh = table2array(x_is_noon55_enh_t);

% Now work towards predicting the last 20 observations.
